# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write  # Needed for the JamesIves action to push to gh-pages

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single build and deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Using a newer Ruby version that comes with newer RubyGems
          bundler-cache: false  # Disable bundler cache initially to update RubyGems
      
      - name: Update RubyGems and Bundler
        run: |
          gem update --system
          gem install bundler
          echo "RubyGems version: $(gem --version)"
          echo "Bundler version: $(bundle --version)"
          
      - name: Install Dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install
        
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          
      - name: List build output
        run: |
          echo "Site files generated:"
          ls -la _site
          echo "Total files: $(find _site -type f | wc -l)"
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site       # The folder to deploy
          branch: gh-pages    # The branch to deploy to
          clean: true         # Automatically remove deleted files from the deployment branch
